"""add duration_seconds

Revision ID: 06f19c85896c
Revises: c8e17e91fa13
Create Date: 2026-06-05 15:51:25.732895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f19c85896c'
down_revision: Union[str, Sequence[str], None] = 'c8e17e91fa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'duration_seconds')
    # ### end Alembic commands ###
