"""initial

Revision ID: 441bd8e53e64
Revises: 
Create Date: 2026-04-25 16:57:48.596807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441bd8e53e64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endpoints', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'link_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['link_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'link_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'chat_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    # ### end Alembic commands ###
