"""add incidents

Revision ID: 9e0bbc8daa4b
Revises: d5d4cb455927
Create Date: 2026-06-05 15:49:48.302738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0bbc8daa4b'
down_revision: Union[str, Sequence[str], None] = 'd5d4cb455927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_endpoints_user_id'), 'endpoints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_user_id'), table_name='endpoints')
    # ### end Alembic commands ###
